<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-03T12:34:16 EDT" name="Suite" finished-at="2024-04-03T12:34:40 EDT" duration-ms="24470">
    <groups>
    </groups>
    <test started-at="2024-04-03T12:34:16 EDT" name="Test" finished-at="2024-04-03T12:34:40 EDT" duration-ms="24470">
      <class name="com.itlearn.testcases.LoginDataProvider">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.itlearn.testcases.LoginDataProvider@26d9b808]" started-at="2024-04-03T12:34:17 EDT" name="setup" finished-at="2024-04-03T12:34:25 EDT" duration-ms="8308" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify(java.lang.String,java.lang.String)[pri:0, instance:com.itlearn.testcases.LoginDataProvider@26d9b808]" started-at="2024-04-03T12:34:28 EDT" name="verify" data-provider="loginData" finished-at="2024-04-03T12:34:34 EDT" duration-ms="5864" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Demo12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123456$]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
        <test-method signature="verify(java.lang.String,java.lang.String)[pri:0, instance:com.itlearn.testcases.LoginDataProvider@26d9b808]" started-at="2024-04-03T12:34:34 EDT" name="verify" data-provider="loginData" finished-at="2024-04-03T12:34:39 EDT" duration-ms="4645" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Demo55]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Login2345#]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.itlearn.testcases.LoginDataProvider.verify(LoginDataProvider.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.itlearn.testcases.LoginDataProvider@26d9b808]" started-at="2024-04-03T12:34:39 EDT" name="teardown" finished-at="2024-04-03T12:34:40 EDT" duration-ms="1015" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.itlearn.testcases.LoginDataProvider -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
